language: julia
os:
    - osx
    - linux
julia:
    - 1.0
    - 1.4
    - nightly

notifications:
  email: false

after_success:
  - julia --project=coverage/ -e 'using Pkg; Pkg.instantiate()'
  - julia --project=coverage/ coverage/coverage.jl
